export enum L  {
  BOOK = 'book',
  UP = 'ltop',
  DOWN = 'lbot',
  SFA = 'sofa',
  SFL = 'sofal',
  SFR = 'sofar',
  PL1 = 'pl1',
  PL2 = 'pl2',
  PL3 = 'pl3',
  PR1 = 'pr1',
  PR2 = 'pr2',
  PR3 = 'pr3',
  TVT = 'tvt',
  TVS = 'tvs',
}

export const lightsConfig = {
  '1': L.TVT,
  '6': L.BOOK,
  '5': L.UP,
  '8': L.DOWN,
  '9': L.SFA,
  '19': L.SFL,
  '20': L.SFR,
  '17': L.PL1,
  '15': L.PL2,
  '18': L.PL3,
  '13': L.PR1,
  '16': L.PR2,
  '14': L.PR3,
  '22': L.TVS,
};