export enum Light  {
  BOOK = 'book',
  BDR = 'bdr',
  UP = 'ltop',
  DOWN = 'lbot',
  SFA = 'sofa',
  SFL = 'sofal',
  SFR = 'sofar',
  PL1 = 'pl1',
  PL2 = 'pl2',
  PL3 = 'pl3',
  PR1 = 'pr1',
  PR2 = 'pr2',
  PR3 = 'pr3',
  TVT = 'tvt',
  TVS = 'tvs',
  TBL = 'tbl',
}

export const lightsConfig = {
  '1': Light.TVT,
  '6': Light.BOOK,
  '7': Light.BDR,
  '5': Light.UP,
  '8': Light.DOWN,
  '9': Light.SFA,
  '19': Light.SFL,
  '20': Light.SFR,
  '17': Light.PL1,
  '15': Light.PL2,
  '18': Light.PL3,
  '13': Light.PR1,
  '16': Light.PR2,
  '14': Light.PR3,
  '22': Light.TVS,
  '26': Light.TBL,
};